CREATE TABLE orders (
    id               VARCHAR(64) PRIMARY KEY,
    idempotency_key  VARCHAR(128) UNIQUE,
    product_id       VARCHAR(64)   NOT NULL,
    quantity         BIGINT        NOT NULL,
    amount           NUMERIC(12,2) NOT NULL,
    status           VARCHAR(32)   NOT NULL,
    payment_deadline TIMESTAMPTZ,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE outbox (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     VARCHAR(64)  NOT NULL,
    topic        VARCHAR(64)  NOT NULL,
    type         VARCHAR(64)  NOT NULL,
    msg_key      VARCHAR(64)  NOT NULL,
    payload      TEXT         NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ
);

CREATE TABLE processed_events (
    event_id     VARCHAR(64) PRIMARY KEY,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
